import logging
from fastapi import APIRouter, HTTPException
from typing import Dict, Any, Optional
from pydantic import BaseModel
from app.schemas.rescreening import ReScreeningTriggerEnum, ReScreeningJob
from app.modules.rescreening.service import (
    trigger_re_screening_job,
    execute_re_screening_job,
    get_all_rescreening_jobs,
    get_coordinator_notifications
)

router = APIRouter(prefix="/rescreening", tags=["rescreening"])
logger = logging.getLogger("clinical_trial_assistant")

class TriggerJobRequest(BaseModel):
    trigger_type: ReScreeningTriggerEnum
    trigger_source_id: str
    patient_id: Optional[str] = None
    trial_id: Optional[str] = None
    idempotency_key: Optional[str] = None


@router.post("/trigger", response_model=Dict[str, Any])
def trigger_job_endpoint(request: TriggerJobRequest):
    """Trigger an automatic re-screening job with idempotency key."""
    try:
        job = trigger_re_screening_job(
            trigger_type=request.trigger_type,
            trigger_source_id=request.trigger_source_id,
            patient_id=request.patient_id,
            trial_id=request.trial_id,
            idempotency_key=request.idempotency_key
        )
        return {
            "success": True,
            "data": job.model_dump(mode="json")
        }
    except Exception as e:
        logger.error(f"Error triggering re-screening job: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/execute/{job_id}", response_model=Dict[str, Any])
def execute_job_endpoint(job_id: str):
    """Execute a pending re-screening job and generate impact summary."""
    try:
        summary = execute_re_screening_job(job_id)
        return {
            "success": True,
            "data": summary.model_dump(mode="json")
        }
    except Exception as e:
        logger.error(f"Error executing re-screening job '{job_id}': {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/jobs", response_model=Dict[str, Any])
def get_jobs_endpoint():
    """Retrieve all re-screening jobs."""
    try:
        jobs = get_all_rescreening_jobs()
        return {
            "success": True,
            "data": [j.model_dump(mode="json") for j in jobs]
        }
    except Exception as e:
        logger.error(f"Error retrieving re-screening jobs: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/notifications", response_model=Dict[str, Any])
def get_notifications_endpoint():
    """Retrieve coordinator notifications generated by re-screening state changes."""
    try:
        notifs = get_coordinator_notifications()
        return {
            "success": True,
            "data": [n.model_dump(mode="json") for n in notifs]
        }
    except Exception as e:
        logger.error(f"Error retrieving coordinator notifications: {e}")
        raise HTTPException(status_code=500, detail=str(e))
